### ISSUE TITLE
Unable to start pull request (nothing to compare)...?

### ISSUE THREAD

**Issue by brethvoice** [geospace-code/matmap3d#1]
I forked the entire repo to https://github.com/brethvoice/matmap3d and made my edits there.  It is literally only adding ",1" inside the three calls to `nan` in ecef2eci.m, lines 20-22, inclusive.

**Comment by scivision** [comment]
thanks !

**Comment by scivision** [comment]
I fixed it in a slightly different way and found another place with the same issue

**Comment by brethvoice** [comment]
@scivision your method was more intuitive and less fragile.  Thanks for the help; next time how do I actually do a pull request, because I was unable to do so this time?

**Comment by scivision** [comment]
I don't know, it may have been a GitHub bug. I haven't had that issue before

**Comment by brethvoice** [comment]
My first foray into the world of pull requests, and it was an epic fail.  Sorry for making you code it for me, @scivision.

**Comment by scivision** [comment]
Well it's quite typical that I edit a PR because often it reveals additional issues that I hadn't realized till then
