### ISSUE TITLE
[Bug]: Incorrect docstring in geodetic2ned.m

### ISSUE THREAD

**Issue by thomas-enevoldsen** [geospace-code/matmap3d#8]
### What happened?

The docstring in geodetic2ned.m is incorrect.

It currently states:

%%% outputs
% * e,n,u:  East, North, Up coordinates of test points (meters)

However, it should be
%%% outputs
% * n,e,d:  North, East, Down coordinates of test points (meters)

The same thing is true for the pages (https://geospace-code.github.io/matmap3d/geodetic2ned.html)

**Comment by utommo** [comment]
Sorry, I didn't add the bug label on purpose. It was more meant as an observation.
